# Permalinks
permalink: pretty


# Configure
timezone: Asia/Shanghai

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus: tangl163

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics:


# Defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"

# Setup
title: "Paul on Programming"
description: "Here lies Balin, son of Fundin, Lord of Moria."
paginate: 5
baseurl: ''

# About/contact

redcarpet:
  extensions: ["fenced_code_blocks", "no_intra_emphasis", "tables", "autolink", "strikethrough"]

webrick:
  headers:
    Cache-Control: false
